packages:
  - ./basic
  - ./solid-element
  - ./solid-start
  - ./with-farm-poku
  - ./with-rspack
  - ./with-vanila-extract
  - ./with-vite-pages

overrides:
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  tmp@<=0.2.3: '>=0.2.4'
