packages:
  - ./basic
  - ./solid-element
  - ./solid-start
  - ./with-farm-poku
  - ./with-rspack
  - ./with-vanila-extract
  - ./with-vite-pages
  - ./tanstack-start-example

overrides:
  '@eslint/compat': '>=2.0.0'
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/js': ^10
  '@rsbuild/plugin-babel': ^1.0.6
  '@rsbuild/plugin-solid': ^1.0.6
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/node': ^24.10.4
  ajv@<8.18.0: '>=8.18.0'
  eslint: ^10
  eslint>ajv: ^6.12.4
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  h3@<=1.15.4: '>=1.15.5'
  minimatch@<10.2.1: '>=10.2.1'
  seroval@<1.4.1: '>=1.4.1'
  tmp@<=0.2.3: '>=0.2.4'
  vite: ^7.3.0
