packages:
  - ./basic
  - ./solid-element
  - ./solid-start
  - ./with-farm-poku
  - ./with-rspack
  - ./with-vanila-extract
  - ./with-vite-pages
  - ./tanstack-start-example

overrides:
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  tmp@<=0.2.3: '>=0.2.4'
  '@types/node': '^24.10.4'
  '@eslint/compat': '^2.0.0'
  '@rsbuild/plugin-babel': '^1.0.6'
  '@rsbuild/plugin-solid': '^1.0.6'
  'vite': '^7.3.0'
